### PR TITLE
Set the default string length to 191 to support more MySQL databases

### PR DESCRIPTION
**Pull request by pachonk**

### CODE REVIEW

**Comment by d4rkd0s** [comment]
@pachonk  What do you mean by "more MySQL databases"? Redundancy? Other versions?

**Comment by d4rkd0s** [comment]
Just deduced this is for MariaDB support based on the merging branch name, if you could write a description in your future PRs it would be much appreciated! :D

**Comment by pachonk** [comment]
@d4rkd0s it is also for other mysql versions do I didn't mention Maria.
Sorry.

**Comment by d4rkd0s** [comment]
@pachonk no problem! I've updated the title of this issue from `Set the default string length to 191 to support more MySQL databases` to `Set the default string length MariaDB Support` for record keeping.

**Comment by pachonk** [comment]
Btw, this does reduce the string length default from 256 to the number in
PR. The other option is explaining MySQL version > and Maria version >

**Comment by d4rkd0s** [comment]
This does limit the JSON solutions for storing invited/accepted/declined users then as well, which means I may have to increase this back up, or have a solution for storing JSON / other methods implemented.

**Comment by pachonk** [comment]
MySQL allows for a json or jsonb column type which also is queryable. You
should basically just have to remove json encode and decode on php side and
it should just work

**Comment by pachonk** [comment]
Otherwise, revert and I'll make the readme state usable versions.

**Comment by d4rkd0s** [comment]
@pachonk Need to write migrations for the current data stored in the string fields. Going to let it be expanded until we have that done.

**Comment by d4rkd0s** [comment]
Reverted for now: 677edec14112e676b5ccc7fd2cf8e8b3cf143a2e

If you want to make this change again, have it along side a solution for the database, like a migration for the strings to JSON columns.

**Pull request merged**
